name: contact_angles
dependencies:
  - numpy
  - scipy
  - scikit-image
  - imageio
  - matplotlib
  - setuptools
  - numba
  - wheel
  - twine
  - pytest
  - pip
  - pip:
    - imageio-ffmpeg
    - pytest-subtests
    - pytest-cov
    - pyautogui
